name: "Features - Release"
on:
  workflow_dispatch:
    inputs:
      run_tests:
        type: boolean
        description: 'run tests'
        default: true

jobs:
  run-tests:
    uses: ./.github/workflows/test.yaml
    name: 🧪 Run tests
    secrets: inherit
    with:
      enabled: ${{ inputs.run_tests }}

  deploy:
    needs: [run-tests]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-24.04
    name: 🚀 Deploy
    permissions:
      contents: write
      pull-requests: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        name: 📩 Checkout repository

      - name: 📦 Publish features
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./src"
          generate-docs: "false"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}